name: 'Repolinter Action'
description: 'Provide a description here'
author: 'New Relic Opensource'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
