name: 'Repolinter Action'
description: 'Runs Repolinter against a repository, then uses the results to open an issue.'
author: 'New Relic Opensource'
inputs:
  config-file:
    required: false
    description: 'The filename of the Repolinter configuration to use, relative to the repository this action is being run on. Mutually exclusive with configUrl.'
  config-url:
    required: false
    description: 'The URL to pull the Repolinter configuration from. The URL must be publicly accessible. Mutually exclusive with configFile.'
  repository:
    required: false
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  output-type:
    required: false
    description: 'Where to push the results from the Repolinter output. Can be "off" (console only) or "issue" (create a github issue).'
    default: 'off'
  output-name:
    required: false
    description: 'The name to use for the issue/PR being created by this action.'
    default: 'Open Source Policy Issues'
  label-name:
    required: false
    description: "What issue label Repolinter should use to mark it's issue/PRs. This label must be unique to repolinter (i.e. no other issues under that label) in order for it's issue management engine to work correctly."
    default: 'repolinter'
  label-color:
    required: false
    description: 'What color to use for the issue/PR label (default is yellow). Must be a hex string (ex "f29513").'
    default: 'fbca04'
runs:
  using: 'node12'
  main: 'dist/index.js'
