name: Repolinter Action
on: 
    workflow_dispatch: {} 

jobs:
  repolint:
    runs-on: ubuntu-latest
    name: Run Repolinter
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Local Action
        uses: DSACMS/repolinter-action@main 
        with:
          output_type: 'pull-request'
          base_branch: 'main'


